version: '3.9'

services:
  db:
    container_name: db
    hostname: db
    image: postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready -U ${DB_USERNAME:-pguser} -d ${DB_NAME:-company_manager}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME:-pguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pgpwd}
      POSTGRES_DB: ${DB_NAME:-company_manager}
    restart: always
    networks:
      - default

#  api:
#    container_name: api
#    hostname: api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    expose:
#      - 8080
#    env_file:
#      - .env
#    environment:
#      DB_HOST: ${DB_HOST:-db}
#      DB_PORT: ${DB_PORT:-5432}
#      DB_USERNAME: ${DB_USERNAME:-pguser}
#      DB_PASSWORD: ${DB_PASSWORD:-pgpwd}
#      DB_NAME: ${DB_NAME:-company}
#    restart: always
#    networks:
#      - default
#    depends_on:
#      - db

networks:
  default:
    driver: bridge
