spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:company_manager}
    username: ${DB_USERNAME:pguser}
    password: ${DB_PASSWORD:pgpwd}
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
