name: Standard

on:
  push:
    branches:
      - main
      - feature/*
      - hotfix/*
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: pgpwd
          POSTGRES_USER: pguser
          POSTGRES_DB: company_manager
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install Dependencies
        run: mvn -B dependency:go-offline --file pom.xml

      - name: Build Application
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test --file pom.xml

#      - name: Sonar Analysis
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ci_docker:
    name: CI Docker
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Build
        run: echo "Building image"
      - name: Push
        run: echo "Pushing image"

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: [ ci, ci_docker ]
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy Infra
        run: echo "Deploying to production"
      - name: Deploy App
        run: echo "Deploying to production"
